/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export interface external {
  "image.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "ingredient.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "knowledge_panels/elements/element.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "knowledge_panels/elements/image_element.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "knowledge_panels/elements/panel_element.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "knowledge_panels/elements/panel_group_element.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "knowledge_panels/elements/table_element.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "knowledge_panels/elements/text_element.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "knowledge_panels/elements/title_element.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "knowledge_panels/panel.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "knowledge_panels/panels.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "packagings/material.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "packagings/packaging_component.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "packagings/packagings_complete.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "packagings/packagings.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "packagings/recycling.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "packagings/shape.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
}

export type operations = Record<string, never>;
