/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export interface external {
  "material-write.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "recycling-write.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "shape-write.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
}

export type operations = Record<string, never>;
