/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Endpoint that serves Prometheus metrics.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hello */
        get: operations["hello__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge_panel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Knowledge Panel
         * @description FacetName is the model that have list of values
         *     facet_tag are the list of values connecting to FacetName
         *     eg:- category/beer, here beer is the value
         */
        get: operations["knowledge_panel_knowledge_panel_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/render-to-html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Render Html
         * @description Render item.html using jinja2
         *     This is helper function to make thing easier while injecting facet_kp in off-server
         */
        get: operations["render_html_render_to_html_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BaseElement
         * @description Element container
         */
        BaseElement: {
            /**
             * Element Type
             * @description The type of the included element object.The type also indicates which field contains the included element object. e.g. if the type is "text", the included element object will be in the "text_element" field.
             */
            element_type: string;
            /**
             * Text Element
             * @description A text in simple HTML format to display.
             */
            text_element: components["schemas"]["BaseTextElement"];
        };
        /**
         * BaseTextElement
         * @description An element with simple HTML to display
         */
        BaseTextElement: {
            /**
             * Html
             * @description Text to display in HTML format
             */
            html?: string;
            /**
             * Source Text
             * @description name of the source
             */
            source_text?: string;
            /**
             * Source Url
             * @description Link to the source
             */
            source_url?: string;
        };
        /**
         * BaseTitleElement
         * @description An element containing a title
         */
        BaseTitleElement: {
            /**
             * Title
             * @description title of the panel
             */
            title: string;
        };
        /** FacetResponse */
        FacetResponse: {
            knowledge_panels?: components["schemas"]["KnowledgePanel"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KnowledgePanel */
        KnowledgePanel: {
            HungerGames?: components["schemas"]["KnowledgePanelItem"];
            Quality?: components["schemas"]["KnowledgePanelItem"];
            LastEdits?: components["schemas"]["KnowledgePanelItem"];
            WikiData?: components["schemas"]["KnowledgePanelItem"];
        };
        /**
         * KnowledgePanelItem
         * @description A Panel, made of multiple sub elements
         */
        KnowledgePanelItem: {
            /** Elements */
            elements?: components["schemas"]["BaseElement"][];
            title_element: components["schemas"]["BaseTitleElement"];
        };
        /**
         * PanelName
         * @description An enumeration.
         * @enum {string}
         */
        PanelName: "last_edits" | "data_quality" | "hunger_game" | "wikidata";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    hello__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    knowledge_panel_knowledge_panel_get: {
        parameters: {
            query: {
                /** @description Facet tag string for the items to search in the database eg:- `category` etc. */
                facet_tag: string;
                /** @description value tag string for the items to search in the database eg:-`en:beers` etc. */
                value_tag?: string;
                /** @description secondary facet tag string for the items to search in the database eg:-`brand` etc. */
                sec_facet_tag?: string;
                /** @description secondary value tag string for the items to search in the database eg:-`lidl` etc. */
                sec_value_tag?: string;
                /** @description To return knowledge panels in native language, default lang: `en`. */
                lang_code?: string;
                /** @description To return knowledge panels for specific country, ex: `france` or `fr`. */
                country?: string;
                /** @description a list of panel names to include, it is incompatible with `exclude` parameter. If neither `include` or `exclude` is provided, we display `hunger_game` and `wikidata` by default. */
                include?: components["schemas"]["PanelName"][];
                /** @description a list of panel names to exclude, it is incompatible with `include` parameter */
                exclude?: components["schemas"]["PanelName"][];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_html_render_to_html_get: {
        parameters: {
            query: {
                /** @description Facet tag string for the items to search in the database eg:- `category` etc. */
                facet_tag: string;
                /** @description value tag string for the items to search in the database eg:-`en:beers` etc. */
                value_tag?: string;
                /** @description secondary facet tag string for the items to search in the database eg:-`brand` etc. */
                sec_facet_tag?: string;
                /** @description secondary value tag string for the items to search in the database eg:-`lidl` etc. */
                sec_value_tag?: string;
                /** @description To return knowledge panels in native language, default lang: `en`. */
                lang_code?: string;
                /** @description To return knowledge panels for specific country, ex: `france` or `fr`. */
                country?: string;
                /** @description a list of panel names to include, it is incompatible with `exclude` parameter. If neither `include` or `exclude` is provided, we display `hunger_game` and `wikidata` by default. */
                include?: components["schemas"]["PanelName"][];
                /** @description a list of panel names to exclude, it is incompatible with `include` parameter */
                exclude?: components["schemas"]["PanelName"][];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
