/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hello */
        get: operations["hello__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authentication
         * @description Authentication: provide user/password and get a bearer token in return
         *
         *     - **username**: Open Food Facts user_id (not email)
         *     - **password**: user password (clear text, but HTTPS encrypted)
         *
         *     token is returned, to be used in later requests with usual "Authorization: bearer token" headers
         */
        post: operations["authentication_auth_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth_by_cookie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authentication By Cookie
         * @description Authentication: provide Open Food Facts session cookie and get a bearer token in return
         *
         *     - **session cookie**: Open Food Facts session cookie
         *
         *     token is returned, to be used in later requests with usual "Authorization: bearer token" headers
         */
        post: operations["authentication_by_cookie_auth_by_cookie_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Product Stats
         * @description Get the list of products with tags statistics
         *
         *     The products list can be limited to some tags (k or k=v)
         */
        get: operations["product_stats_products_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Product List
         * @description Get the list of products matching k or k=v
         */
        get: operations["product_list_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/{product}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Product Tags List
         * @description Get a list of existing tags for a product, optionally filtering by specific keys.
         */
        get: operations["product_tags_list_product__product__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/{product}/{k}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Product Tag
         * @description Get a specific tag or tag hierarchy on a product
         *
         *     - /product/xxx/key returns only the requested key
         *     - /product/xxx/key* returns the key and subkeys (key:subkey)
         */
        get: operations["product_tag_product__product___k__get"];
        put?: never;
        post?: never;
        /**
         * Product Tag Delete
         * @description Delete a product tag
         */
        delete: operations["product_tag_delete_product__product___k__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product/{product}/{k}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Product Tag List Versions
         * @description Get a list of all versions of a tag for a product
         */
        get: operations["product_tag_list_versions_product__product___k__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/product": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Product Tag Update
         * @description Update a product tag
         *
         *     - **product**: which product
         *     - **k**: which key for the tag
         *     - **v**: which value to set for the tag
         *     - **version**: must be equal to previous version + 1
         *     - **owner**: None or empty for public tags, or your own user_id
         */
        put: operations["product_tag_update_product_put"];
        /**
         * Product Tag Add
         * @description Create a new product tag (version=1)
         *
         *     - **product**: which product
         *     - **k**: which key for the tag
         *     - **v**: which value to set for the tag
         *     - **version**: none or empty or 1
         *     - **owner**: none or empty for public tags, or your own user_id
         *
         *     Be aware it's not possible to create the same tag twice. Though, you can update
         *     a tag and add multiple values the way you want (don't forget to document how); comma
         *     separated list is a good option.
         */
        post: operations["product_tag_add_product_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Keys List
         * @description Get the list of keys with statistics, with an optional search filter.
         *
         *     The keys list can be restricted to private tags from some owner
         */
        get: operations["keys_list_keys_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/values/{k}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Unique Values
         * @description Get the unique values of a given property and the corresponding number of products
         *
         *     - **k**: The property key to get unique values for
         *     - **owner**: None or empty for public tags, or your own user_id
         *     - **q**: Filter values by a query string
         *     - **limit**: Maximum number of values to return (default: 50; max: 1000)
         */
        get: operations["get_unique_values_values__k__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pong
         * @description Check server health
         */
        get: operations["pong_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/property/check-clash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Property Clash
         * @description Check for potential clashes when renaming a property
         *
         *     Returns information about products that would be affected by the rename:
         *     - **old_property**: The current property name
         *     - **new_property**: The target property name
         *
         *     Returns counts and list of conflicting products where both properties exist
         */
        post: operations["check_property_clash_admin_property_check_clash_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/property/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rename Property
         * @description Rename a property across all products
         *
         *     When renaming a property that already exists:
         *     - If both properties have the same value: keep one entry
         *     - If both properties have different values: keep the original property's value
         *
         *     - **old_property**: The current property name
         *     - **new_property**: The target property name
         */
        post: operations["rename_property_admin_property_rename_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/property": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Property
         * @description Delete a property from all products
         *
         *     - **property**: The property name to delete
         */
        delete: operations["delete_property_admin_property_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Info
         * @description Get current user roles (admin, moderator, user)
         */
        get: operations["get_user_info_user_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/value/replace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace Value
         * @description Replace a value for a specific property across all products
         *
         *     - **property**: The property name
         *     - **old_value**: The value to replace
         *     - **new_value**: The new value
         */
        post: operations["replace_value_admin_value_replace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Value
         * @description Delete a specific value for a property from all products
         *
         *     - **property**: The property name
         *     - **value**: The value to delete
         */
        delete: operations["delete_value_admin_value_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_authentication_auth_post */
        Body_authentication_auth_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /** Client Secret */
            client_secret?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HelloResponse */
        HelloResponse: {
            /** Message */
            message: string;
        };
        /** KeyStats */
        KeyStats: {
            /** K */
            k: string;
            /** Count */
            count: number;
            /** Values */
            values: number;
        };
        /** PingResponse */
        PingResponse: {
            /** Ping */
            ping: string;
        };
        /** ProductList */
        ProductList: {
            /** Product */
            product: string;
            /** K */
            k: string;
            /** V */
            v: string;
        };
        /** ProductStats */
        ProductStats: {
            /** Product */
            product: string;
            /** Keys */
            keys: number;
            /** Editors */
            editors: number;
            /**
             * Last Edit
             * Format: date-time
             */
            last_edit: string;
        };
        /** ProductTag */
        ProductTag: {
            /** Product */
            product: string;
            /** K */
            k: string;
            /** V */
            v: string;
            /**
             * Owner
             * @default
             */
            owner: string;
            /**
             * Version
             * @default 1
             */
            version: number;
            /** Editor */
            editor?: string | null;
            /** Last Edit */
            last_edit?: string | null;
            /**
             * Comment
             * @default
             */
            comment: string | null;
        };
        /** PropertyClashCheck */
        PropertyClashCheck: {
            /** Products With Both */
            products_with_both: number;
            /** Products With Old Only */
            products_with_old_only: number;
            /** Products With New Only */
            products_with_new_only: number;
            /** Conflicting Products */
            conflicting_products: unknown[];
        };
        /** PropertyClashCheckRequest */
        PropertyClashCheckRequest: {
            /** Old Property */
            old_property: string;
            /** New Property */
            new_property: string;
        };
        /** PropertyDeleteRequest */
        PropertyDeleteRequest: {
            /** Property */
            property: string;
        };
        /** PropertyRenameRequest */
        PropertyRenameRequest: {
            /** Old Property */
            old_property: string;
            /** New Property */
            new_property: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValueCount */
        ValueCount: {
            /** V */
            v: string;
            /** Product Count */
            product_count: number;
        };
        /** ValueDeleteRequest */
        ValueDeleteRequest: {
            /** Property */
            property: string;
            /** Value */
            value: string;
        };
        /** ValueRenameRequest */
        ValueRenameRequest: {
            /** Property */
            property: string;
            /** Old Value */
            old_value: string;
            /** New Value */
            new_value: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    hello__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HelloResponse"];
                };
            };
        };
    };
    authentication_auth_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_authentication_auth_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    authentication_by_cookie_auth_by_cookie_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    product_stats_products_stats_get: {
        parameters: {
            query?: {
                owner?: unknown;
                k?: unknown;
                v?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductStats"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    product_list_products_get: {
        parameters: {
            query?: {
                owner?: unknown;
                k?: unknown;
                v?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    product_tags_list_product__product__get: {
        parameters: {
            query?: {
                owner?: string;
                /** @description Comma-separated list of keys to filter by. If not provided, all keys are returned. */
                keys?: string;
            };
            header?: never;
            path: {
                product: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductTag"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    product_tag_product__product___k__get: {
        parameters: {
            query?: {
                owner?: unknown;
            };
            header?: never;
            path: {
                product: string;
                k: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductTag"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    product_tag_delete_product__product___k__delete: {
        parameters: {
            query: {
                version: number;
                owner?: unknown;
            };
            header?: never;
            path: {
                product: string;
                k: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    product_tag_list_versions_product__product___k__versions_get: {
        parameters: {
            query?: {
                owner?: unknown;
            };
            header?: never;
            path: {
                product: string;
                k: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductTag"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    product_tag_update_product_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductTag"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    product_tag_add_product_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductTag"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    keys_list_keys_get: {
        parameters: {
            query?: {
                q?: string | null;
                owner?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyStats"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_unique_values_values__k__get: {
        parameters: {
            query?: {
                owner?: string;
                q?: string;
                limit?: number;
            };
            header?: never;
            path: {
                k: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValueCount"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pong_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResponse"];
                };
            };
        };
    };
    check_property_clash_admin_property_check_clash_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyClashCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyClashCheck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_property_admin_property_rename_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyRenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_property_admin_property_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_info_user_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    replace_value_admin_value_replace_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValueRenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_value_admin_value_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValueDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
