/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export interface external {
  "image_element.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "panel_element.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "panel_group_element.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "table_element.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
  "text_element.yaml": {
    paths: Record<string, never>;
    webhooks: Record<string, never>;
    components: Record<string, never>;
  };
}

export type operations = Record<string, never>;
