name: JS Checks

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 23.x, 24.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install and enable Corepack
        run: |
          npm install -g corepack --force
          corepack enable

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint code
        run: yarn lint

      - name: Check code formatting
        run: yarn format

      - name: Build
        run: yarn build

      # Run tests
      - name: Run tests
        run: yarn test

  coverage:
    name: Coverage Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install and enable Corepack
        run: |
          npm install -g corepack --force
          corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build

      - name: Run tests with coverage
        run: yarn test --coverage

      - name: Write coverage report to GitHub Summary
        uses: livewing/lcov-job-summary@v1.2.0
        with:
          lcov: "coverage/lcov.info"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  docs:
    name: Build Docs
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install and enable Corepack
        run: |
          npm install -g corepack --force
          corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build

      - name: Build documentation
        run: yarn build:docs

      - name: Upload docs
        uses: actions/upload-pages-artifact@v5
        with:
          path: "docs"

  deploy_docs:
    name: Deploy Docs
    runs-on: ubuntu-latest
    needs: docs

    # only deploy docs when changes are pushed to the develop branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Deploy documentation to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
