name: release-please
on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.release-please.outputs.release_created }}
      sha: ${{ steps.release-please.outputs.sha }}
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          target-branch: develop
