/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v2/product/{barcode}": {
    /**
     * Get information for a specific product by barcode
     * @description A product can be fetched via its unique barcode.
     * It returns all the details of that product response.
     */
    get: operations["get-product-by-barcode"];
  };
  "/api/v2/product/{barcode}?fields=knowledge_panels": {
    /**
     * Get Knowledge panels for a specific product by barcode
     * (special case of get product)
     *
     * @description Knowledge panels gives high leve informations about a product,
     * ready to display.
     * This is used by open food facts website,
     * and by the official mobile application
     */
    get: operations["get-product-by-barcode-knowledge-panels"];
  };
  "/cgi/product_image_upload.pl": {
    /**
     * Add a Photo to an Existing Product
     * @description Photos are source and proof of data.
     * The first photo uploaded for a product is
     * auto-selected as the product’s “front” photo.'
     */
    post: operations["get-cgi-product_image_upload.pl"];
  };
  "/cgi/ingredients.pl": {
    /**
     * Performing OCR on a Product
     * @description Open Food Facts uses optical character recognition (OCR) to retrieve nutritional data and other information from the product labels.
     */
    get: operations["get-cgi-ingredients.pl"];
  };
  "/cgi/product_image_crop.pl": {
    /**
     * Rotate A Photo
     * @description Although we recommend rotating photos manually and uploading a new version of the image,
     * the OFF API allows you to make api calls to automate this process.
     * You can rotate existing photos by setting the angle to 90º, 180º, or 270º clockwise.
     */
    get: operations["get-cgi-product_image_crop.pl"];
    /**
     * Crop A Photo
     * @description Cropping is only relevant for editing existing products.
     * You cannot crop an image the first time you upload it to the system.
     */
    post: operations["post-cgi-product_image_crop.pl"];
  };
  "/cgi/product_image_unselect.pl": {
    /** Unselect A Photo */
    post: {
      requestBody?: {
        content: {
          "multipart/form-data": external["requestBodies/unselect_a_photo.yaml"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /**
               * @description status of the unselect operation
               * @example status ok
               */
              status?: string;
              /**
               * @description status code of the operation
               * @example 0
               */
              status_code?: number;
              /**
               * @description image field that was unselected
               * @example front_fr
               */
              imagefield?: string;
            };
          };
        };
      };
    };
  };
  "/cgi/product_jqm2.pl": {
    /**
     * Add or Edit A Product
     * @description If the barcode exists then you will be editing the existing product,
     * However if it doesn''t you will be creating a new product with that unique barcode,
     * and adding properties to the product.
     */
    post: operations["post-cgi-product_jqm2.pl"];
  };
  "/api/v2/search": {
    /**
     * Search for Products
     * @description Search request allows you to get the nutritional data of products that match your search criteria.
     * It allows you create many custom APIs for your use case.
     * If the search query parameter has 2 possible values, they are seperated by a comma(,).
     * When filtering via a parameter that has different language codes like `fr`, `de` or `en`, specify the language code in the parameter name e.g `categories_tags_en`
     */
    get: operations["get-search"];
  };
  "/cgi/suggest.pl": {
    /**
     * Get Suggestions to Aid Adding/Editing Products
     * @description For example , Dave is looking for packaging_shapes that contain the term "fe",
     * all packaging_shapes containing "fe" will be returned.
     * This is useful if you have a search in your application,
     * for a specific product field.
     */
    get: operations["get-cgi-suggest.pl"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    "Product-Base": external["schemas/product_base.yaml"];
    "Product-Misc": external["schemas/product_misc.yaml"];
    "Product-Tags": external["schemas/product_tags.yaml"];
    "Product-Nutrition": external["schemas/product_nutrition.yaml"];
    "Product-Ingredients": external["schemas/product_ingredients.yaml"];
    "Product-Images": external["schemas/product_images.yaml"];
    "Product-Eco-Score": external["schemas/product_ecoscore.yaml"];
    "Product-Metadata": external["schemas/product_meta.yaml"];
    "Product-Data-Quality": external["schemas/product_quality.yaml"];
    "Product-Knowledge-Panels": external["schemas/product_knowledge_panels.yaml"];
    Product: external["schemas/product.yaml"];
  };
  responses: never;
  parameters: {
    id: string;
    /** @description Barcode of the product */
    code: string;
    process_image: string;
    ocr_engine: string;
    imgid: string;
    angle: string;
    /**
     * @description The allowed values  used to sort/order the search results.
     *
     * * `product_name` sorts on name
     * * `ecoscore_score`, `nova_score`, `nutriscore_score` rank on the [Eco-Score](https://world.openfoodfacts.org/eco-score-the-environmental-impact-of-food-products), [Nova](https://world.openfoodfacts.org/nova), or [Nutri-Score](https://world.openfoodfacts.org/nutriscore)
     * * `scans_n`, `unique_scans_n` and `popularity_key` are about product popularity: number of scans on unique scans, rank of product
     * * `created_t`, `last_modified_t`, are about creation and modification dates
     * * `nothing`, tells not to sort at all (because if you do not provide the sort_by argument we default to sorting on popularity (for food) or last modification date)
     */
    sort_by?: "product_name" | "last_modified_t" | "scans_n" | "unique_scans_n" | "created_t" | "completeness" | "popularity_key" | "nutriscore_score" | "nova_score" | "nothing" | "ecoscore_score";
    /**
     * @description The fields to be returned from the product object can also be limited.
     * If not specified, it returns the entire product object response.
     */
    fields?: string;
    tagtype?: string;
    term?: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export interface external {
  "examples/get_product_by_barcode_spread.yaml": unknown
  "requestBodies/add_or_edit_a_product.yaml": {
    /**
     * @description The barcode of the product to be added or edited
     * @example 0074570036004
     */
    code: string;
    /**
     * @description A valid username.
     * @example myusername
     */
    user_id: string;
    /**
     * @description A valid corresponding password.
     * @example mypassword
     */
    password: string;
    /**
     * @description The brands of the product (comma separated list of values).
     * @example Häagen-Dazs,General-mills
     */
    brands?: unknown;
    /**
     * @description The labels of the product (comma separated list of values).
     * @example Kosher,Ferroro
     */
    labels?: unknown;
    /**
     * @description The categories of the product (comma separated list of values).
     * @example Desserts,Frozen foods
     */
    categories?: unknown;
    /**
     * @description Packaging type, format, material.
     * The [v3 API documentation](https://openfoodfacts.github.io/openfoodfacts-server/api/ref-v3/#operation/post-api-v3-product-barcode)
     * has a more structured data for `packaging`.
     *
     * @example Frozen
     */
    packaging?: string;
  };
  "requestBodies/add_photo_to_existing_product.yaml": {
    /**
     * @description Barcode of the product
     *
     * @example 3017620422003
     */
    code: string;
    /**
     * @description Indicates the type of the image and the corresponding language. It should
     * be in the format `{IMAGE_TYPE}_{LANG}` format, where `IMAGE_TYPE` is one
     * of `front|ingredients|nutrition|packaging|other` and `LANG` is the 2
     * letter language code. Use `other` if you don't want the image to be
     * selected. Note that the first image of a product is always selected as front
     * picture.
     *
     * @example front_en
     */
    imagefield: string;
    /**
     * Format: binary
     * @description This field must contain image binary content.
     * The format and extension must be one of gif|jpeg|jpg|png|heic.
     * This field is dynamic and dependent on the value of imagefield in the
     * request body. It wil be imgupload_the value of the imagefield stated
     * earlier. For example, if `imagefield=front_en`, the name of this field
     * should be `imageupload_front_en`.
     */
    imgupload_front_en: string;
  };
  "requestBodies/crop_a_photo.yaml": {
    /**
     * @description Barcode of the product.
     * @example 04963406
     */
    code: string;
    /**
     * @description identifier of the image to select, it should be a number
     * @example 2
     */
    imgid: number;
    /**
     * @description identifier of the selected image field, should be in the format
     * `{IMAGE_TYPE}_{LANG}` format, where `IMAGE_TYPE` is one of
     * `front|ingredients|nutrition|packaging|other` and `LANG` is the 2 letter
     * language code.
     * Note that if you select an image for the main language of the product (ex:
     * `ingredients_it` if `it` is the main language), this image will be
     * displayed on Product Opener for all languages (ex: on
     * `https://fr.openfoodfacts.org`, unless `ingredients_fr` exists).
     *
     * @example front_en
     */
    id: string;
    /**
     * @description X origin coordinate of the crop, it must be lower than x2
     * @example 0
     */
    x1?: number;
    /**
     * @description Y origin coordinate of the crop, it must be lower than y2
     * @example 0
     */
    y1?: number;
    /**
     * @description X end coordinate of the crop, it must be higher than x1
     * @example 145
     */
    x2?: number;
    /**
     * @description Y end coordinate of the crop, it must be higher than y1
     * @example 145
     */
    y2?: number;
    /**
     * @description angle of the rotation to apply on the selected image.
     * passing `90` as value rotate the image 90 degrees counter-clockwise.
     *
     * @example 0
     */
    angle?: number;
    /**
     * @description whether the selected image should be normalized using ImageMagick
     * @example false
     * @enum {string}
     */
    normalize?: "true" | "false";
    /**
     * @description whether the source image should be white magiced (background removal) using
     * ImageMagick.
     *
     * @default false
     * @enum {string}
     */
    white_magic?: "true" | "false";
  };
  "requestBodies/unselect_a_photo.yaml": {
    /**
     * @description code of the product
     * @example 4251105501381
     */
    code?: string;
    /**
     * @description image field (image id) of the photo to unselect
     * @example front_fr
     */
    id?: string;
  };
  "responses/add_or_edit_a_product.yaml": {
    /** @example fields saved */
    status_verbose?: string;
    /** @example 1 */
    status?: number;
  };
  "responses/add_photo_to_existing_product.yaml": {
    files?: {
        /** @example /product/3017620422003/nutella-ferrero */
        url?: string;
        /** @example */
        filename?: string;
        /** @example Nutella - Ferrero - 400g */
        name?: string;
        /** @example /images/products/301/762/042/2003/123.100.jpg */
        thumbnailUrl?: string;
        /** @example 3017620422003 */
        code?: string;
      }[];
    image?: {
      /** @example 123.100.jpg */
      thumb_url?: string;
      /** @example 123 */
      imgid?: number;
      /** @example 123.400.jpg */
      crop_url?: string;
    };
    /** @example 123 */
    imgid?: number;
    /** @example status ok */
    status?: string;
    /** @example front_en */
    imagefield?: string;
    /** @example 3017620422003 */
    code?: string;
  };
  "responses/get_product_by_barcode_base.yaml": {
    /**
     * @description Barcode of the product
     * (can be EAN-13 or internal codes for some food stores).
     * For products without a barcode, Open Food Facts assigns a
     * number starting with the 200 reserved prefix.
     */
    code?: string;
    status?: number;
    status_verbose?: string;
  };
  "responses/get_product_by_barcode.yaml": external["responses/get_product_by_barcode_base.yaml"] & {
    product?: external["schemas/product.yaml"];
  };
  "responses/ocr_on_product.yaml": {
    /** @example 1 */
    status?: number;
  };
  "responses/rotate_a_photo.yaml": {
    /** @example status ok */
    status?: string;
    /** @example nutrition_fr */
    imagefield?: string;
    image?: {
      /** @example nutrition_fr.67.400.jpg */
      display_url?: string;
    };
  };
  "responses/search_for_products.yaml": {
    /**
     * @description Total number of products found
     *
     * @example 2701
     */
    count?: number;
    /**
     * @description Page number of returned results
     *
     * @example 1
     */
    page?: number;
    /**
     * @description Total number of pages
     *
     * @example 24
     */
    page_count?: number;
    /**
     * @description Number of products per pages
     *
     * @example 24
     */
    page_size?: number;
    /** @description The products matching the query corresponding to current page */
    products?: external["schemas/product.yaml"][];
    /** @example 0 */
    skip?: number;
  };
  "schemas/agribalyse.yaml": {
    agribalyse_food_code?: string;
    co2_agriculture?: number;
    co2_consumption?: number;
    co2_distribution?: number;
    co2_packaging?: number;
    co2_processing?: number;
    co2_total?: number;
    co2_transportation?: number;
    code?: string;
    dqr?: string;
    ef_agriculture?: number;
    ef_consumption?: number;
    ef_distribution?: number;
    ef_packaging?: number;
    ef_processing?: number;
    ef_total?: number;
    ef_transportation?: number;
    is_beverage?: number;
    /**
     * @description This can be returned in many other languages
     * like name_fr (for french).
     */
    name_en?: string;
    score?: number;
    version?: string;
  };
  "schemas/image_role.yaml": {
    /**
     * @description The angle of the image rotation (if it was rotated).
     * @example 0
     */
    angle?: number;
    /** @example full */
    coordinates_image_size?: string;
    /** @example 0x0--1--1 */
    geometry?: string;
    /**
     * @description The id of the original/source image that was selected to edit(rotate, normalize etc) to produce this new image.
     * @example 121
     */
    imgid?: string;
    /**
     * @description Normalize colors.
     * @example null
     */
    normalize?: null;
    /** @example 420 */
    rev?: string;
    /**
     * @description The available image sizes for the product (both reduced and full).
     * The reduced images are the ones with numbers as the key( 100, 200 etc)
     * while the full images have `full` as the key.
     */
    sizes?: {
      100?: external["schemas/image_size.yaml"];
      200?: external["schemas/image_size.yaml"];
      400?: external["schemas/image_size.yaml"];
      full?: external["schemas/image_size.yaml"];
    };
    /**
     * @description Photo on white background : Try to remove the background.
     *
     * @example null
     */
    white_magic?: null;
    /** @example -1 */
    x1?: string;
    /** @example -1 */
    x2?: string;
    /** @example -1 */
    y1?: string;
    /** @example -1 */
    y2?: string;
  };
  "schemas/image_size.yaml": {
    /**
     * @description The height of the reduced/full image in pixels.
     *
     * @example 400
     */
    h?: number;
    /**
     * @description The width of the reduced/full image in pixels.
     *
     * @example 255
     */
    w?: number;
  };
  "schemas/image_urls.yaml": Record<string, never>;
  "schemas/image.yaml": {
    /**
     * @description The available image sizes for the product (both reduced and full).
     * The reduced images are the ones with numbers as the key( 100, 200 etc)
     * while the full images have `full` as the key.
     */
    sizes?: {
      /**
       * @description properties of fullsize image
       * **TODO** explain how to compute name
       */
      full?: external["schemas/image_size.yaml"];
    };
    /**
     * @description The time the image was uploaded (as unix timestamp).
     *
     * @example 1457680652
     */
    uploaded_t?: string;
    /**
     * @description The contributor that uploaded the image.
     *
     * @example openfoodfacts-contributors
     */
    uploader?: string;
  };
  "schemas/ingredient.yaml": {
      id?: string;
      /** @description Sub ingredients composing this ingredients. */
      ingredients?: external["schemas/ingredient.yaml"];
      percent?: number;
      percent_estimate?: number;
      percent_max?: number;
      percent_min?: number;
      text?: string;
      vegan?: string;
      vegetarian?: string;
    }[];
  "schemas/knowledge_panels/elements/element.yaml": {
    /**
     * @description The type of the included element object.
     * The type also indicates which field contains the included element object.
     * e.g. if the type is "text", the included element object will be in the "text_element" field.
     *
     * Note that in the future, new type of element may be added,
     * so your code should ignore unrecognized types, and unknown properties.
     *
     * TODO: add Map type
     *
     * @enum {unknown}
     */
    type: "text" | "image" | "action" | "panel" | "panel_group" | "table";
    text_element?: external["schemas/knowledge_panels/elements/text_element.yaml"];
    image_element?: external["schemas/knowledge_panels/elements/image_element.yaml"];
    action_element?: string;
    panel_element?: external["schemas/knowledge_panels/elements/panel_element.yaml"];
    panel_group_element?: external["schemas/knowledge_panels/elements/panel_group_element.yaml"];
    table_element?: external["schemas/knowledge_panels/elements/table_element.yaml"];
  };
  "schemas/knowledge_panels/elements/image_element.yaml": {
    /** @description full URL of the image */
    url?: string;
    /**
     * @description Width of the image.
     *
     * This is just a suggestion coming from the server,
     * the client may choose to use its own dimensions for the image.
     */
    width?: number;
    /**
     * @description Height of the image.
     *
     * This is just a suggestion coming from the server,
     * the client may choose to use its own dimensions for the image.
     */
    height?: number;
    /** @description Alt Text of the image. */
    alt_text?: string;
  };
  "schemas/knowledge_panels/elements/panel_element.yaml": {
    /** @description The id of the panel to include. The id is the key of the panel in the panels object returned in the knowledge_panels field. */
    panel_id?: string;
  };
  "schemas/knowledge_panels/elements/panel_group_element.yaml": {
    title?: string;
    /** @description The ids of the panels to include. The ids are the keys of the panels in the panels object returned in the knowledge_panels field. */
    panel_ids?: string[];
  };
  "schemas/knowledge_panels/elements/table_element.yaml": {
    /** @description An id for the table. */
    id?: string;
    /** @description Title of the column. */
    title?: string;
    rows?: string;
    columns?: {
        type?: string;
        text?: string;
        text_for_small_screens?: string;
        style?: string;
        column_group_id?: string;
        shown_by_default?: boolean;
      }[];
  };
  "schemas/knowledge_panels/elements/text_element.yaml": {
    /**
     * @description the type of text, might influence the way you display it.
     *
     * @enum {string}
     */
    type?: "summary" | "warning" | "notes";
    /** @description Text to display in HTML format. */
    html?: string;
    /** @description Language of the text. The name of the language is returned in the language requested when making the API call. e.g. if the text is in Polish, and the requested language is French, the language field will contain "Polonais" (French for "Polish"). Only set for specific fields such as the list of ingredients of a product. */
    language?: string;
    /** @description 2 letter language code for the text. Only set for specific fields such as the list of ingredients of a product. */
    lc?: string;
    /** @description id of the field used to edit this text in the product edit API. */
    edit_field_id?: string;
    /** @description Type of the product field. */
    edit_field_type?: string;
    /** @description Current value of the product field. This may differ from the html field which can contain extra formating. */
    edit_field_value?: string;
    /**
     * @description Link to the source
     * @example https://en.wikipedia.org/wiki/Sodium acetate
     */
    source_url?: string;
    /**
     * @description name of the source
     * @example Wikipedia
     */
    source_text?: string;
    /**
     * @description Source locale name
     * @example en
     */
    source_lc?: string;
    /**
     * @description Human readable source locale name
     * @example English
     */
    source_language?: string;
  };
  "schemas/knowledge_panels/elements/title_element.yaml": {
    title?: string;
    /**
     * @description Indicates that the panel corresponds to a A to E grade such as the Nutri-Score of the Eco-Score.
     * @enum {string}
     */
    grade?: "a" | "b" | "c" | "d" | "e" | "unknown";
    icon_url?: string;
    icon_color_from_evaluation?: string;
    /** @description If set to "small", the icon should be displayed at a small size. */
    icon_size?: string;
    /**
     * @description Used to indicate a special type for the title, such as "grade" for Nutri-Score and Eco-Score.
     * @example grade
     */
    type?: string;
  };
  "schemas/knowledge_panels/panel.yaml": {
    /** @description Type of the panel. If set to "card", the panel and its sub-panels should be displayed in a card. If set to "inline", the panel should have its content always displayed. */
    type?: string;
    /** @description If true, the panel is to be displayed already expanded. If false, only the title should be displayed, and the user should be able to click or tap it to open the panel and display the elements. */
    expanded?: boolean;
    /** @description If set to "large", the content of the panel should be expanded on large screens, but it should still be possible to unexpand it. */
    expand_for?: string;
    title_element?: external["schemas/knowledge_panels/elements/title_element.yaml"];
    /** @description An ordered list of elements to display in the content of the panel. */
    elements?: external["schemas/knowledge_panels/elements/element.yaml"][];
    /**
     * @description a message level, as levels we use in log.
     * It might help theming the panel visualy
     *
     * @example info
     */
    level?: string;
    /**
     * @description size is either empty (normal display)
     * or small to indicate a panel that should have a smaller font size
     *
     * @example small
     * @enum {string}
     */
    size?: "small";
    topics?: string[];
  };
  "schemas/knowledge_panels/panels.yaml": {
    readonly additionalProperties?: external["schemas/knowledge_panels/panel.yaml"];
  };
  "schemas/packagings/material.yaml": {
    /** @description Canonical id of the entry in the taxonomy. If the value cannot be mapped to a taxonomy entry, the value will be the name of the entry in its original language prefixed by the language 2 letter code and a colon. */
    id?: string;
    /** @description Name of the entry in the language requested in the tags_lc field of the request. This field is returned only of tags_lc is specified. If the translation is not available, or if the entry does not exist in the taxonomy, the value will be the name of the entry in its original language prefixed by the language 2 letter code and a colon. */
    lc_name?: string;
  };
  "schemas/packagings/packaging_component.yaml": {
    /** @description umber of units of this packaging component contained in the product (e.g. 6 for a pack of 6 bottles) */
    number_of_units?: number;
    shape?: external["schemas/packagings/shape.yaml"];
    material?: external["schemas/packagings/material.yaml"];
    recycling?: external["schemas/packagings/recycling.yaml"];
    /** @description Quantity (weight or volume) of food product contained in the packaging component. (e.g. 75cl for a wine bottle) */
    quantity_per_unit?: string;
    /** @description Value parsed from the quantity field. */
    quantity_per_unit_value?: number;
    /** @description Unit parsed and normalized from the quantity field. */
    quantity_per_unit_unit?: string;
    /** @description Weight (as specified by the manufacturer) of one unit of the empty packaging component (in grams). (e.g. for a 6 pack of 1.5l water bottles, it might be 30, the weight in grams of 1 empty water bottle without its cap which is a different packaging component). */
    weight_specified?: number;
    /** @description Weight (as measured by one or more users) of one unit of the empty packaging component (in grams). (e.g. for a 6 pack of 1.5l water bottles, it might be 30, the weight in grams of 1 empty water bottle without its cap which is a different packaging component). */
    weight_measured?: number;
    /** @description Weight (as estimated from similar products) of one unit of the empty packaging component (in grams). (e.g. for a 6 pack of 1.5l water bottles, it might be 30, the weight in grams of 1 empty water bottle without its cap which is a different packaging component). */
    weight_estimated?: number;
    /** @description Weight of one unit of the empty packaging component. */
    weight?: number;
    /** @description Indicates which field was used to populate the "weight" field. Either "specified", "measured", or "estimated" */
    weight_source_id?: string;
  };
  "schemas/packagings/packagings_complete.yaml": number;
  "schemas/packagings/packagings.yaml": readonly external["schemas/packagings/packaging_component.yaml"][];
  "schemas/packagings/recycling.yaml": {
    /** @description Canonical id of the entry in the taxonomy. If the value cannot be mapped to a taxonomy entry, the value will be the name of the entry in its original language prefixed by the language 2 letter code and a colon. */
    id?: string;
    /** @description Name of the entry in the language requested in the tags_lc field of the request. This field is returned only of tags_lc is specified. If the translation is not available, or if the entry does not exist in the taxonomy, the value will be the name of the entry in its original language prefixed by the language 2 letter code and a colon. */
    lc_name?: string;
  };
  "schemas/packagings/shape.yaml": {
    /** @description Canonical id of the entry in the taxonomy. If the value cannot be mapped to a taxonomy entry, the value will be the name of the entry in its original language prefixed by the language 2 letter code and a colon. */
    id?: string;
    /** @description Name of the entry in the language requested in the tags_lc field of the request. This field is returned only of tags_lc is specified. If the translation is not available, or if the entry does not exist in the taxonomy, the value will be the name of the entry in its original language prefixed by the language 2 letter code and a colon. */
    lc_name?: string;
  };
  "schemas/product_base.yaml": {
    /** @description Abbreviated name in requested language */
    abbreviated_product_name?: string;
    /**
     * @description barcode of the product (can be EAN-13 or internal codes for some food stores),
     * for products without a barcode,
     * Open Food Facts assigns a number starting with the 200 reserved prefix
     */
    code?: string;
    codes_tags?: string[];
    /**
     * @description Legal name of the product as regulated
     * by the European authorities.
     */
    generic_name?: string;
    /**
     * @description internal identifier for the product, usually set to the value of `code`,
     * except on the producers platform where it is prefixed by the owner
     */
    id?: string;
    /**
     * @description Main language of the product.
     * This is a duplicate of `lang` property (for historical reasons).
     */
    lc?: string;
    /**
     * @description Main language of the product.
     *
     * This should be the main language of product packaging (if one is predominant).
     *
     * Main language is also used to decide which ingredients list to parse.
     */
    lang?: string;
    /** @description Nova group as an integer from 1 to 4. See https://world.openfoodfacts.org/nova */
    nova_group?: number;
    nova_groups?: string;
    obsolete?: string;
    /**
     * @description A date at which the product was declared obsolete.
     * This means it's not produced any more.
     */
    obsolete_since_date?: string;
    /** @description The name of the product */
    product_name?: string;
    /**
     * @description The name of the product can also
     * be in many other languages like
     * product_name_fr (for French).
     */
    product_name_en?: string;
    /**
     * @description The size in g or ml for the whole product.
     * It's a normalized version of the quantity field.
     *
     * @example 500
     */
    product_quantity?: string;
    /**
     * @description The unit (either g or ml) for the correponding product_quantity.
     *
     * @example g
     */
    product_quantity_unit?: string;
    /** @description Quantity and Unit. */
    quantity?: string;
  };
  "schemas/product_ecoscore.yaml": {
    /**
     * @description An object about a lot of details about data needed for Eco-Score computation
     * and complementary data of interest.
     */
    ecoscore_data?: {
      adjustments?: {
        origins_of_ingredients?: {
          aggregated_origins?: {
              origin?: string;
              percent?: number;
            }[];
          epi_score?: number;
          epi_value?: number;
          origins_from_origins_field?: string[];
          transportation_scores?: Record<string, never>;
          transportation_values?: Record<string, never>;
          values?: Record<string, never>;
          warning?: string;
        };
        packaging?: {
          non_recyclable_and_non_biodegradable_materials?: number;
          packagings?: {
              ecoscore_material_score?: number;
              ecoscore_shape_ratio?: number;
              material?: string;
              shape?: string;
            }[];
          score?: number;
          value?: number;
          warning?: string;
        };
        production_system?: {
          /** @example vegan, fat free, Kosher */
          labels?: string[];
          value?: number;
          warning?: string;
        };
        threatened_species?: {
          ingredient?: string;
          value?: number;
        };
      };
      agribalyse?: external["schemas/agribalyse.yaml"];
      grade?: string;
      grades?: Record<string, never>;
      missing?: {
        labels?: number;
        origins?: number;
        packagings?: number;
      };
      missing_data_warning?: number;
      previous_data?: {
        grade?: string;
        score?: number;
        agribalyse?: external["schemas/agribalyse.yaml"];
      };
      score?: number;
      scores?: Record<string, never>;
      status?: string;
    };
    ecoscore_extended_data_version?: string;
    environment_impact_level?: string;
    environment_impact_level_tags?: Record<string, never>[];
  };
  "schemas/product_extended.yaml": {
    additives_original_tags?: string[];
    additives_prev_original_tags?: string[];
    added_countries_tags?: Record<string, never>[];
    allergens_from_ingredients?: string;
    allergens_from_user?: string;
    amino_acids_prev_tags?: Record<string, never>[];
    amino_acids_tags?: Record<string, never>[];
    carbon_footprint_percent_of_known_ingredients?: number;
    categories_properties?: {
      "agribalyse_food_code:en"?: string;
      "agribalyse_proxy_food_code:en"?: string;
      "ciqual_food_code:en"?: string;
    };
    categories_properties_tags?: string[];
    category_properties?: {
      [key: string]: string;
    };
    ciqual_food_name_tags?: string[];
    /**
     * @description the category to use for comparison.
     *
     * **TODO** explain how it is chosen.
     */
    compared_to_category?: string;
    conservation_conditions?: string;
    /** @description Contact info of customer service. */
    customer_service?: string;
    expiration_date?: string;
    /** @description link to the product on the website of the producer */
    link?: string;
    main_countries_tags?: Record<string, never>[];
    minerals_prev_tags?: Record<string, never>[];
    minerals_tags?: Record<string, never>[];
    /**
     * @description Those are fields provided by the producer (through producers platform),
     * and the value he provided.
     */
    owner_fields?: {
      /**
       * @description you can retrieve all kind of properties, the same as on the parent object (the product).
       * It's not processed entries (like tags for example) but raw ones.
       */
      additionalProperties?: number | string | Record<string, never>;
    };
    /** @description Detail of ingredients or processing that makes the products having Nova 3 or 4 */
    nova_groups_markers?: {
      /** @description Markers of level 3 */
      3?: string[][];
      /** @description Markers of level 4 */
      // @ts-expect-error TODO: fix this
      4?: external["schemas/product_extended.yaml"]["nova_groups_markers"]["3"]["items"][];
    };
    nucleotides_tags?: Record<string, never>[];
    origin?: string;
    /**
     * @description Country, state, or city where the product can be purchased.
     *
     * @example Paris
     */
    purchase_places?: string;
    purchase_places_tags?: string[];
    /**
     * @description Distributor name.
     *
     * @example Walmart
     */
    stores?: string;
    stores_tags?: string[];
    traces_from_ingredients?: string;
    traces_from_user?: string;
  };
  "schemas/product_images.yaml": {
    image_front_small_url?: string;
    image_front_thumb_url?: string;
    image_front_url?: string;
    image_nutrition_small_url?: string;
    image_nutrition_thumb_url?: string;
    image_nutrition_url?: string;
    image_small_url?: string;
    image_thumb_url?: string;
    image_url?: string;
    /** @description This contains properties for all images contained on the product. */
    images?: {
      /** @description This represents an image uploaded for this product. */
      1?: external["schemas/image.yaml"];
      /** @description This represents an image (or part of it) selected for a specific role on this product. */
      front?: external["schemas/image_role.yaml"];
    };
    last_image_dates_tags?: string[];
    last_image_t?: number;
    selected_images?: {
      /** @description URLs of thumbnails image of image of type `image_type` */
      front?: {
        /** @description Thumbnail urls of product image (front) adapted to display on product page */
        display?: external["schemas/image_urls.yaml"];
        /** @description Thumbnail urls of product image (front) adapted to display on product list page */
        small?: external["schemas/image_urls.yaml"];
        /** @description Thumbnail urls of product image (front) in smallest format */
        thumb?: external["schemas/image_urls.yaml"];
      };
    };
  };
  "schemas/product_ingredients.yaml": {
    additives_tags?: string[];
    /** @description comma separated list of allergens */
    allergens?: string;
    /** @description language in which `allergens` where input */
    allergens_lc?: string;
    allergens_hierarchy?: string[];
    allergens_tags?: string[];
    ingredients?: external["schemas/ingredient.yaml"];
    ingredients_analysis?: {
      "en:palm-oil"?: string[];
      "en:vegan-status-unknown"?: string[];
      "en:vegetarian-status-unknown"?: string[];
    };
    ingredients_analysis_tags?: string[];
    ingredients_from_or_that_may_be_from_palm_oil_n?: number;
    ingredients_from_palm_oil_n?: number;
    ingredients_from_palm_oil_tags?: Record<string, never>[];
    ingredients_hierarchy?: string[];
    ingredients_n?: number;
    ingredients_n_tags?: string[];
    ingredients_original_tags?: string[];
    ingredients_percent_analysis?: number;
    ingredients_tags?: string[];
    /**
     * @description Language that was used to parse the ingredient list. If `ingredients_text` is available
     * for the product main language (`lang`), `ingredients_lc=lang`, otherwise we look at
     * `ingredients_text` fields for other languages and set `ingredients_lc` to the first
     * non-empty `ingredient_text`.
     */
    ingredients_lc?: string;
    /**
     * @description Raw list of ingredients. This will get automatically
     * parsed and get used to compute the Eco-Score or find allergens, etc..
     *
     * It's a copy of ingredients_text in the main language of the product (see `lang` proprety).
     *
     * @example Farine de blé* 67,4%, sucre de canne*, huile de tournesol oléique*, graines de chia* 5,2%, son de blé*, oranges déshydratées * 0,9%, farine de riz*, poudres à lever (acide citrique, carbonates de sodium), arôme naturel d'orange.
     */
    ingredients_text?: string;
    /**
     * @description Same text as `ingredients_text` but where allergens have HTML elements around them to identify them
     *
     * @example Farine de <span class="allergen">blé*</span> 67,4%, sucre de canne*, huile de tournesol oléique*, graines de chia* 5,2%, <span class="allergen">son de blé*</span>, oranges déshydratées * 0,9%, farine de riz*, poudres à lever (acide citrique, carbonates de sodium), arôme naturel d'orange.
     */
    ingredients_text_with_allergens?: string;
    ingredients_that_may_be_from_palm_oil_n?: number;
    ingredients_that_may_be_from_palm_oil_tags?: Record<string, never>[];
    ingredients_with_specified_percent_n?: number;
    ingredients_with_specified_percent_sum?: number;
    ingredients_with_unspecified_percent_n?: number;
    ingredients_with_unspecified_percent_sum?: number;
    known_ingredients_n?: number;
    /** @description Origins of ingredients */
    origins?: string;
    origins_hierarchy?: Record<string, never>[];
    origins_lc?: string;
    origins_tags?: Record<string, never>[];
    /**
     * @description List of substances that might cause allergies
     * that are present in trace amounts in the product
     * (this does not include the ingredients, as they
     * are not only present in trace amounts).
     * It is taxonomized with the allergens taxonomy.
     */
    traces?: string;
    traces_hierarchy?: Record<string, never>[];
    traces_lc?: string;
    traces_tags?: Record<string, never>[];
    unknown_ingredients_n?: number;
  };
  "schemas/product_knowledge_panels.yaml": {
    knowledge_panels?: external["schemas/knowledge_panels/panels.yaml"];
  };
  "schemas/product_meta.yaml": {
    /**
     * @description Date when the product was added (UNIX timestamp format).
     * See also `entry_dates_tags`
     *
     * @example 1457680652
     */
    created_t?: number;
    /** @description The contributor who added the product first. */
    creator?: string;
    /** @description List of editors who edited the product. */
    editors_tags?: string[];
    informers_tags?: string[];
    interface_version_created?: string;
    interface_version_modified?: string;
    languages?: Record<string, never>;
    /** @description Same as `languages` but by language code, instead of language tags */
    languages_codes?: Record<string, never>;
    languages_hierarchy?: string[];
    languages_tags?: string[];
    last_edit_dates_tags?: string[];
    last_editor?: string;
    /**
     * @description The username of the user who last modified the product.
     *
     * @example sebleouf
     */
    last_modified_by?: string;
    /** @description Date when the product page was last modified. */
    last_modified_t?: number;
    /** @description Id of the producer in case he provides his own data about a product (producer platform). */
    owner?: string;
    /** @description Tagyfied version of owner */
    owners_tags?: string;
    photographers_tags?: string[];
    /** @description revision number of this product version (each edit adds a revision) */
    rev?: number;
    sources?: ({
        fields?: string[];
        id?: string;
        images?: Record<string, never>[];
        import_t?: number;
        manufacturer?: number | string;
        name?: string;
        source_licence?: string;
        source_licence_url?: string;
        url?: null | string;
      })[];
    sources_fields?: {
      "org-gs1"?: {
        gln?: string;
        gpcCategoryCode?: string;
        gpcCategoryName?: string;
        isAllergenRelevantDataProvided?: string;
        lastChangeDateTime?: string;
        partyName?: string;
        productionVariantDescription?: string;
        publicationDateTime?: string;
      };
    };
    teams?: string;
    teams_tags?: string[];
    update_key?: string;
  };
  "schemas/product_misc.yaml": {
    /** @description Number of food additives. */
    additives_n?: number;
    checked?: string;
    complete?: number;
    completeness?: number;
    /** @description See also: `ecoscore_tags` */
    ecoscore_grade?: string;
    /** @description See also: `ecoscore_tags` */
    ecoscore_score?: number;
    food_groups?: string;
    food_groups_tags?: string[];
    /** @description Traffic light indicators on main nutrients levels */
    nutrient_levels?: {
      /** @enum {string} */
      fat?: "low" | "moderate" | "high";
      /** @enum {string} */
      salt?: "low" | "moderate" | "high";
      /** @enum {string} */
      "saturated-fat"?: "low" | "moderate" | "high";
      /** @enum {string.} */
      sugars?: "low" | "moderate" | "high";
    };
    /**
     * @description Recycling instructions as raw text, e.g. Plastic
     * bottle to recycle, Plastic cap to recycle.
     * This will get automatically parsed and
     * will be used to compute the Eco-Score.
     * You can either request it (if it exists) or
     * send it in a specific language.
     *
     * @example packaging_text_en
     */
    packaging_text?: string;
    packagings?: external["schemas/packagings/packagings.yaml"];
    packagings_complete?: external["schemas/packagings/packagings_complete.yaml"];
    /** @description Category of food according to [French Nutrition and Health Program](https://fr.wikipedia.org/wiki/Programme_national_nutrition_sant%C3%A9) */
    pnns_groups_1?: string;
    pnns_groups_1_tags?: string[];
    /** @description Sub Category of food according to [French Nutrition and Health Program](https://fr.wikipedia.org/wiki/Programme_national_nutrition_sant%C3%A9) */
    pnns_groups_2?: string;
    pnns_groups_2_tags?: string[];
    popularity_key?: number;
    popularity_tags?: string[];
    scans_n?: number;
    unique_scans_n?: number;
    /**
     * @description Normalized version of serving_size.
     * Note that this is NOT the number of servings by product.
     * <small>(in perl, see `normalize_serving_size`)</small>
     */
    serving_quantity?: string;
    /**
     * @description The unit (either g or ml) for the correponding serving_quantity.
     *
     * @example g
     */
    serving_quantity_unit?: string;
    /**
     * @description Serving size text (generally in g or ml).
     * We expect a quantity + unit but the user is free to input any string.
     */
    serving_size?: string;
  };
  "schemas/product_nutrition.yaml": {
    /**
     * @description When a product does not have nutrition data displayed on the
     * packaging, the user can check the field "Nutrition facts are
     * not specified on the product".
     * By doing so, the no_nutrition_data field takes the value "on".
     * This case is frequent (thousands of products).
     *
     * @example on
     */
    no_nutrition_data?: string;
    /**
     * @description The nutrition data on the package can be per serving or per 100g.
     *
     * This is essential to understand if `<nutrient>_value` and `<nutrient>`
     * values in `nutriments` applies for a serving or for 100g.
     *
     * **IMPORTANT:**
     * When writing products,
     * this setting applies to all existing nutrients values for the product,
     * not only the nutrient values sent in the write request.
     * So it should not be changed unless all nutrients values are provided
     * with values that match the nutrition_data_per field.
     *
     * @enum {string}
     */
    nutrition_data_per?: "serving" | "100g";
    /**
     * @description The nutrition data for prepared product on the package (if any) can be per serving or per 100g.
     *
     * This is essential to understand if `<nutrient>_prepared_value` and `<nutrient>_prepared`
     * values in `nutriments` applies for a serving or for 100g.
     *
     * See also important note on `nutrition_data_per`.
     *
     * @enum {string}
     */
    nutrition_data_prepared_per?: "serving" | "100g";
    /**
     * @description All known nutrients for the product.
     *
     * Note that each nutrients are declined with a variety of suffixes like `_100g`, `_serving`,
     * see patternProperties below.
     *
     * A specific `_unit` is the unit used to measure the nutrient.
     *
     * Beware that some properties are to be interpreted based upon `nutrition_data_per` value.
     *
     * Also for products that have a nutrition table for prepared product
     * (eg. the nutrition facts for a bowl of milk with cocoa powder),
     * a `_prepared` suffix is added (before other suffixes).
     *
     * **FIXME** add more nutrients with description.
     */
    nutriments?: {
      /**
       * @description Quantity of alcohol
       *
       * (per 100g or per serving) in a standard unit (g or ml)
       */
      alcohol?: number;
      carbohydrates?: number;
      /**
       * @description It is the same as `energy-kj` if we have it, or computed from `energy-kcal` otherwise
       *
       * (per 100g or per serving) in kj
       */
      energy?: number;
      /** @description energy_value will be equal to energy-kj_value if we have it or to energy-kcal_value otherwise */
      energy_value?: number;
      /**
       * @description Equal to energy-kj_unit if we have it or to energy-kcal_unit otherwise
       *
       * @enum {string}
       */
      energy_unit?: "kcal" | "kj";
      /**
       * @description energy in kcal, if it is specified
       *
       * (per 100g or per serving) in a standard unit (g or ml)
       */
      "energy-kcal"?: number;
      /**
       * @description energy in kj, if it is specified
       *
       * (per 100g or per serving) in a standard unit (g or ml)
       */
      "energy-kj"?: number;
      fat?: number;
      /**
       * @description An estimate, from the ingredients list of the percentage of fruits, vegetable and legumes.
       * This is an important information for Nutri-Score (2023 version) computation.
       */
      "fruits-vegetables-legumes-estimate-from-ingredients"?: number;
      /**
       * @description An estimate, from the ingredients list of the percentage of fruits, vegetable and nuts.
       * This is an important information for Nutri-Score (2021 version) computation.
       */
      "fruits-vegetables-nuts-estimate-from-ingredients"?: number;
      "nova-group"?: number;
      /**
       * @description Experimental nutrition score derived from
       * the UK FSA score and adapted for the French market
       * (formula defined by the team of Professor Hercberg).
       */
      "nutrition-score-fr"?: unknown;
      proteins?: number;
      salt?: number;
      "saturated-fat"?: number;
      sodium?: number;
      sugars?: number;
      "carbon-footprint-from-known-ingredients_product"?: number;
      "carbon-footprint-from-known-ingredients_serving"?: number;
      /**
       * @description erythritol is a polyol which is not providing any energy.
       * As such, it needs not be taken into account when computing
       * the energy of a product. Eryhtritol is now displayed on
       * nutrition facts sheet of some products, mainly in the USA.
       * This value is entered either by contributors, either by
       * imports.
       *
       * @example 12.5
       */
      erythritol?: number;
    };
    /**
     * @description Detail of data the Nutri-Score was computed upon.
     *
     * **TODO** document each property
     */
    nutriscore_data?: {
      energy?: number;
      energy_points?: number;
      energy_value?: number;
      fiber?: number;
      fiber_points?: number;
      fiber_value?: number;
      fruits_vegetables_nuts_colza_walnut_olive_oils?: number;
      fruits_vegetables_nuts_colza_walnut_olive_oils_points?: number;
      fruits_vegetables_nuts_colza_walnut_olive_oils_value?: number;
      grade?: string;
      is_beverage?: number;
      is_cheese?: number;
      is_fat?: number;
      is_water?: number;
      negative_points?: number;
      positive_points?: number;
      proteins?: number;
      proteins_points?: number;
      proteins_value?: number;
      saturated_fat?: number;
      saturated_fat_points?: number;
      saturated_fat_ratio?: number;
      saturated_fat_ratio_points?: number;
      saturated_fat_ratio_value?: number;
      saturated_fat_value?: number;
      score?: number;
      sodium?: number;
      sodium_points?: number;
      sodium_value?: number;
      sugars?: number;
      sugars_points?: number;
      sugars_value?: number;
    };
    /**
     * @description Nutri-Score for the product as a letter.
     *
     * See https://world.openfoodfacts.org/nutriscore.
     *
     * @enum {string}
     */
    nutriscore_grade?: "a" | "b" | "c" | "d" | "e";
    /** @description Nutri-Score for the product as an integer (see also `nutriscore_grade`). */
    nutriscore_score?: number;
    nutriscore_score_opposite?: number;
    /**
     * @description Nutrition grade (‘a’ to ‘e’),
     * https://world.openfoodfacts.org/nutriscore.
     */
    nutrition_grade_fr?: string;
    /**
     * @description Nutrition grades as a comma separated list.
     *
     * Some products with multiple components might have multiple Nutri-Score
     */
    nutrition_grades?: string;
    nutrition_grades_tags?: string[];
    nutrition_score_beverage?: number;
    nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients?: number;
    nutrition_score_warning_fruits_vegetables_nuts_estimate_from_ingredients_value?: number;
    nutrition_score_warning_no_fiber?: number;
    other_nutritional_substances_tags?: Record<string, never>[];
    unknown_nutrients_tags?: Record<string, never>[];
    vitamins_tags?: Record<string, never>[];
  };
  "schemas/product_quality.yaml": {
    data_quality_bugs_tags?: Record<string, never>[];
    data_quality_errors_tags?: Record<string, never>[];
    data_quality_info_tags?: string[];
    data_quality_tags?: string[];
    data_quality_warnings_tags?: string[];
    /** @description Source of data imported from producers. */
    data_sources?: string;
    data_sources_tags?: string[];
    last_check_dates_tags?: string[];
    last_checked_t?: number;
    last_checker?: string;
    /**
     * @description comma separated list of values indicating some states of the product,
     * like things to be done, or to be completed.
     * See [states taxonomy](https://static.openfoodfacts.net/data/taxonomies/states.json)
     */
    states?: string;
    states_hierarchy?: string[];
    states_tags?: string[];
    /** @description Information about different aspect of the product */
    misc_tags?: string[];
  };
  "schemas/product_tags.yaml": {
    brands?: string;
    brands_tags?: string[];
    categories?: string;
    categories_hierarchy?: string[];
    categories_lc?: string;
    categories_tags?: string[];
    checkers_tags?: string[];
    cities?: string;
    cities_tags?: Record<string, never>[];
    correctors_tags?: string[];
    /** @description List of countries where the product is sold. */
    countries?: string;
    countries_hierarchy?: string[];
    countries_lc?: string;
    countries_tags?: string[];
    /**
     * @description All ecoscore of a product.
     * Most of the time it's only one value,
     * but it might eventually be more for products composed of sub-products.
     * See also: `ecoscore_score`, `ecoscore_grade`.
     */
    ecoscore_tags?: string[];
    /**
     * @description Packager code.
     *
     * @example EMB 2013330
     */
    emb_codes?: string;
    emb_codes_orig?: string;
    emb_codes_tags?: Record<string, never>[];
    labels?: string;
    labels_hierarchy?: string[];
    labels_lc?: string;
    labels_tags?: string[];
    /**
     * @description The data as a series of tag: `yyyy-mm-dd`, `yyyy-mm`, `yyyy`
     *
     * @example [
     *   "2016-03-11",
     *   "2016-03",
     *   "2016"
     * ]
     */
    entry_dates_tags?: string[];
    /** @description Places where the product was manufactured or transformed. */
    manufacturing_places?: string;
    manufacturing_places_tags?: Record<string, never>[];
    nova_groups_tags?: string[];
    nutrient_levels_tags?: string[];
  };
  "schemas/product.yaml": external["schemas/product_base.yaml"] & external["schemas/product_misc.yaml"] & external["schemas/product_tags.yaml"] & external["schemas/product_images.yaml"] & external["schemas/product_ecoscore.yaml"] & external["schemas/product_ingredients.yaml"] & external["schemas/product_nutrition.yaml"] & external["schemas/product_quality.yaml"] & external["schemas/product_extended.yaml"] & external["schemas/product_meta.yaml"] & external["schemas/product_knowledge_panels.yaml"];
  "schemas/tags_parameters.yaml": {
    /**
     * @description The additives_tags in english of product(s) you are searching for.
     * The [OFF App](https://world.openfoodfacts.org/additives) has a list of possible values for `additives`.
     */
    additives_tags?: unknown;
    /**
     * @description The allergens_tags in english of product(s) you are searching for.
     * The [OFF App](https://world.openfoodfacts.org/allergens) has a list of possible values for `allergens`.
     */
    allergens_tags?: unknown;
    /**
     * @description The brands_tags of product(s) you are searching for.
     * The [OFF App](https://world.openfoodfacts.org/brands) has a list of possible values for `brands`.
     */
    brands_tags?: unknown;
    /**
     * @description The category of product(s) you are searching for.
     * The [OFF App](https://world.openfoodfacts.org/categories) has a list of possible values for `categories`.
     */
    categories_tags?: unknown;
    /**
     * @description The countries_tags_en of product(s) you are searching for.
     * The [OFF App](https://world.openfoodfacts.org/countries) shows a list of possible values for `countries`.
     */
    countries_tags?: unknown;
    /** @description The emb_codes_tags of product(s) you are searching for. */
    emb_codes_tags?: unknown;
    /**
     * @description The labels_tags in english of product(s) you are searching for.
     * The [OFF App](https://world.openfoodfacts.org/labels) has a list of possible values for `labels`.
     */
    labels_tags?: unknown;
    /**
     * @description The manufacturing_places_tags of product(s) you are searching for.
     * The [OFF App](https://world.openfoodfacts.org/manufacturing-places) has a list of possible values for `manufacturing-places`.
     */
    manufacturing_places_tags?: unknown;
    /**
     * @description The nutrition_grades_tags of product(s) you are searching for.
     * The [OFF App](https://world.openfoodfacts.org/nutrition-grades) has a list of possible values for `nutrition-grades`.
     */
    nutrition_grades_tags?: unknown;
    /** @description The origins_tags of product(s) you are searching for. */
    origins_tags?: unknown;
    /**
     * @description The packaging_tag in german of product(s) you are searching for.
     * The [OFF App](https://world.openfoodfacts.org/packaging) has a list of possible values for `packaging`.
     */
    packaging_tags?: unknown;
    /** @description The purchase_places_tags of product(s) you are searching for. */
    purchase_places_tags?: unknown;
    /**
     * @description The states_tags in english of product(s) you are searching for.
     * The [OFF App](https://world.openfoodfacts.org/states) has a list of possible values for `states`.
     */
    states_tags?: unknown;
    /** @description The stores_tags of product(s) you are searching for. */
    stores_tags?: unknown;
    /**
     * @description The traces_tags of product(s) you are searching for.
     * The [OFF App](https://world.openfoodfacts.org/traces) shows a list of possible values for `traces`.
     */
    traces_tags?: unknown;
    /** @description You can add a language code to a specific tag to query it in a specific language */
    tag_name_with_language_code?: unknown;
  }
}

export interface operations {

  /**
   * Get information for a specific product by barcode
   * @description A product can be fetched via its unique barcode.
   * It returns all the details of that product response.
   */
  "get-product-by-barcode": {
    parameters: {
      path: {
        /** @description The barcode of the product to be fetched */
        barcode: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": external["responses/get_product_by_barcode.yaml"];
        };
      };
    };
  };
  /**
   * Get Knowledge panels for a specific product by barcode
   * (special case of get product)
   *
   * @description Knowledge panels gives high leve informations about a product,
   * ready to display.
   * This is used by open food facts website,
   * and by the official mobile application
   */
  "get-product-by-barcode-knowledge-panels": {
    parameters: {
      path: {
        /** @description The barcode of the product to be fetched */
        barcode: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": external["responses/get_product_by_barcode_base.yaml"] & {
            product?: external["schemas/product_knowledge_panels.yaml"];
          };
        };
      };
    };
  };
  /**
   * Add a Photo to an Existing Product
   * @description Photos are source and proof of data.
   * The first photo uploaded for a product is
   * auto-selected as the product’s “front” photo.'
   */
  "get-cgi-product_image_upload.pl": {
    requestBody?: {
      content: {
        "multipart/form-data": external["requestBodies/add_photo_to_existing_product.yaml"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": external["responses/add_photo_to_existing_product.yaml"];
        };
      };
    };
  };
  /**
   * Performing OCR on a Product
   * @description Open Food Facts uses optical character recognition (OCR) to retrieve nutritional data and other information from the product labels.
   */
  "get-cgi-ingredients.pl": {
    parameters: {
      query: {
        id: components["parameters"]["id"];
        code: components["parameters"]["code"];
        process_image: components["parameters"]["process_image"];
        ocr_engine: components["parameters"]["ocr_engine"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": external["responses/ocr_on_product.yaml"];
        };
      };
    };
  };
  /**
   * Rotate A Photo
   * @description Although we recommend rotating photos manually and uploading a new version of the image,
   * the OFF API allows you to make api calls to automate this process.
   * You can rotate existing photos by setting the angle to 90º, 180º, or 270º clockwise.
   */
  "get-cgi-product_image_crop.pl": {
    parameters: {
      query: {
        code: components["parameters"]["code"];
        id: components["parameters"]["id"];
        imgid: components["parameters"]["imgid"];
        angle: components["parameters"]["angle"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": external["responses/rotate_a_photo.yaml"];
        };
      };
    };
  };
  /**
   * Crop A Photo
   * @description Cropping is only relevant for editing existing products.
   * You cannot crop an image the first time you upload it to the system.
   */
  "post-cgi-product_image_crop.pl": {
    requestBody: {
      content: {
        "multipart/form-data": external["requestBodies/crop_a_photo.yaml"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /**
   * Add or Edit A Product
   * @description If the barcode exists then you will be editing the existing product,
   * However if it doesn''t you will be creating a new product with that unique barcode,
   * and adding properties to the product.
   */
  "post-cgi-product_jqm2.pl": {
    requestBody?: {
      content: {
        "multipart/form-data": external["requestBodies/add_or_edit_a_product.yaml"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": external["responses/add_or_edit_a_product.yaml"];
        };
      };
    };
  };
  /**
   * Search for Products
   * @description Search request allows you to get the nutritional data of products that match your search criteria.
   * It allows you create many custom APIs for your use case.
   * If the search query parameter has 2 possible values, they are seperated by a comma(,).
   * When filtering via a parameter that has different language codes like `fr`, `de` or `en`, specify the language code in the parameter name e.g `categories_tags_en`
   */
  "get-search": {
    parameters: {
      query?: {
        fields?: components["parameters"]["fields"];
        sort_by?: components["parameters"]["sort_by"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": external["responses/search_for_products.yaml"];
        };
      };
    };
  };
  /**
   * Get Suggestions to Aid Adding/Editing Products
   * @description For example , Dave is looking for packaging_shapes that contain the term "fe",
   * all packaging_shapes containing "fe" will be returned.
   * This is useful if you have a search in your application,
   * for a specific product field.
   */
  "get-cgi-suggest.pl": {
    parameters: {
      query?: {
        tagtype?: components["parameters"]["tagtype"];
        term?: components["parameters"]["term"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": unknown[];
        };
      };
    };
  };
}
